sudo: required

language: minimal

services:
  - docker

install:
  - make docker
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  
script:
  - make docker-cross

after_success:
  provider: script
  on:
    branch: master
  script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:  
  provider: releases
  skip_cleanup: true
  api_key: $API_KEY
  file_glob: true
  file: dist/*
  on:
    repo: arminc/clair-scanner
    tags: true